#!/bin/bash
# Build bitcoin.conf from the environment, then run bitcoind in the foreground.
#
# RPC is bound to the container network only. It is never published to the host
# in the compose file, and must never be.
set -euo pipefail

DATADIR=/data
CONF="$DATADIR/bitcoin.conf"

# RPC auth: if no user/password is supplied, bitcoind generates a .cookie in the
# datadir and dependents read it. That is the pattern the official Datum package
# uses against the official Bitcoin package, and it means no RPC secret has to be
# generated, stored, or shared by us at all.
: "${BLAKE2B_HEADLINE:?BLAKE2B_HEADLINE is required, and must not be empty}"

if [ -z "${BLAKE2B_HEADLINE// /}" ]; then
    echo "FATAL: BLAKE2B_HEADLINE is empty. An empty headline satisfies the node's" >&2
    echo "       startup check but makes the consensus rule a no-op, because" >&2
    echo "       std::search with an empty needle always matches. Refusing." >&2
    exit 1
fi

CHAIN="${CHAIN:-regtest}"
PRUNE="${PRUNE:-0}"
ACTIVATION_HEIGHT="${BLAKE2B_ACTIVATION_HEIGHT:-}"
# Space-separated host:port entries to dial in addition to the chain's own seeds.
ADDNODES="${ADDNODES:-}"

case "$CHAIN" in
    regtest|testnet4) ;;
    main|mainnet)
        echo "FATAL: this build refuses mainnet (init.cpp:1077, 'This release" >&2
        echo "       candidate only supports test networks'). Nothing here can" >&2
        echo "       override that, and it should not." >&2
        exit 1 ;;
    *)
        echo "FATAL: unsupported CHAIN='$CHAIN'. Use regtest or testnet4." >&2
        exit 1 ;;
esac

{
    echo "# generated by entrypoint, do not edit"
    echo "${CHAIN}=1"
    echo "server=1"
    echo "printtoconsole=1"
    [ -n "${RPC_USER:-}" ] && echo "rpcuser=${RPC_USER}"
    [ -n "${RPC_PASSWORD:-}" ] && echo "rpcpassword=${RPC_PASSWORD}"
    echo "blake2b_headline=${BLAKE2B_HEADLINE}"
    [ "$PRUNE" != "0" ] && echo "prune=${PRUNE}"
    # Regtest only: fastprune shrinks block files so a short chain can actually
    # be pruned. On testnet4 it would just produce a great many tiny files.
    [ "$CHAIN" = "regtest" ] && [ "${FASTPRUNE:-0}" != "0" ] && echo "fastprune=1"
    echo "fallbackfee=0.0001"
    echo
    echo "[${CHAIN}]"
    echo "rpcbind=0.0.0.0"
    echo "rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}"
    # The internal ports stay the same on every chain, rather than following
    # each chain's default. They are this package's contract with dependents,
    # and StartOS gives every package its own bridge address, so there is
    # nothing to collide with. A dependent should not have to re-read a port
    # because the operator switched chains.
    echo "rpcport=18443"
    echo "port=18444"
    # Regtest only. `-testactivationheight` is read by CRegTestParams and nowhere
    # else, so on testnet4 bitcoind accepts it, logs it, and ignores it: the
    # height stays the compiled-in 149537. Writing it there would be config that
    # looks effective and is not, so it is not written.
    if [ "$CHAIN" = "regtest" ] && [ -n "$ACTIVATION_HEIGHT" ]; then
        echo "testactivationheight=blake2b@${ACTIVATION_HEIGHT}"
    fi
    for node in $ADDNODES; do
        echo "addnode=${node}"
    done
    [ -n "${BLOCKNOTIFY_URL:-}" ] && echo "blocknotify=wget -q -T 2 -O /dev/null ${BLOCKNOTIFY_URL}"
} > "$CONF"

echo "knots-blake2b: pinned commit $(cat /etc/knots-pinned-commit)"
if [ "$CHAIN" = "regtest" ]; then
    activation_note="${ACTIVATION_HEIGHT:-none}"
else
    activation_note="149537 (compiled in, not configurable)"
fi
echo "knots-blake2b: chain=${CHAIN} prune=${PRUNE} activation=${activation_note}"
echo "knots-blake2b: addnodes=${ADDNODES:-none}"

exec bitcoind -datadir="$DATADIR" "$@"
