#!/bin/bash
# Build bitcoin.conf from the environment, then run bitcoind in the foreground.
#
# RPC is bound to the container network only. It is never published to the host
# in the compose file, and must never be.
set -euo pipefail

DATADIR=/data
CONF="$DATADIR/bitcoin.conf"

# RPC auth: if no user/password is supplied, bitcoind generates a .cookie in the
# datadir and dependents read it. That is the pattern the official Datum package
# uses against the official Bitcoin package, and it means no RPC secret has to be
# generated, stored, or shared by us at all.

# One chain: BLAKE2b on mainnet.
#
# This file used to select between regtest, testnet4 and mainnet, and most of its
# length was that choice: a chain-dependent conf section, a headline that was
# consensus on one chain and ignored on another, an activation height settable on
# one chain and compiled in on the others, a curated peer list for the chain whose
# DNS seeds returned the wrong network, and a fallback fee for chains with no fee
# history. The lab chains existed to prove the fork worked before it had a public
# chain to run on. It has had one since 2026-08-30.
#
# So none of the following is configurable any more, and none of it can be got
# wrong: the activation height (961640) and the headline that block committed to
# are both compiled into chainparams as of this pin. `blake2b_headline` is not
# written at all now. It is a regtest-only option in this release, ignored on
# mainnet, and writing an ignored option only invites someone to change it.
#
# No `addnode` list ships either, and that is deliberate. net.cpp queries every
# DNS seed as `x<SeedsServiceFlags()>.<seed>`, which on this build is x10000009:
# NODE_NETWORK | NODE_WITNESS | NODE_BLAKE2B. Two of mainnet's seeds answer that
# prefix with fork nodes. Measured on 2026-08-30: all ten addresses they returned
# were on the BLAKE2b chain, and a node started with no peers configured found
# the chain by itself.
#
# Do not be tempted to seed from gossip instead. Both chains share magic bytes
# and port 8333, so one round of getaddr yielded 7349 candidates of which a
# 60-peer sample had none on the fork. The service-bit filter is the only thing
# that separates them.

# Pruned unless told otherwise, on every platform including a plain `docker run`.
# This node is meant to sit alongside a node on the other chain, and two full
# copies of a ~960k-block chain do not fit on the servers this is for. 0 keeps
# the whole chain; anything else is a budget in MiB that bitcoind enforces
# itself. 1 is bitcoind's manual mode and is not offered anywhere: it reports the
# node as pruned while never discarding anything, so it grows without bound.
PRUNE="${PRUNE:-5000}"

# Space-separated host:port entries to dial in addition to mainnet's own seeds.
ADDNODES="${ADDNODES:-}"

{
    echo "# generated by entrypoint, do not edit"
    # No chain selector line. Mainnet is bitcoind's default: there is no
    # `mainnet=1` option and writing one is a startup error. Its config section
    # is `[main]`, which is why that is spelled out below and not derived from
    # any chain name.
    echo "server=1"
    echo "printtoconsole=1"
    [ -n "${RPC_USER:-}" ] && echo "rpcuser=${RPC_USER}"
    [ -n "${RPC_PASSWORD:-}" ] && echo "rpcpassword=${RPC_PASSWORD}"
    [ "$PRUNE" != "0" ] && echo "prune=${PRUNE}"
    echo
    echo "[main]"
    # When pruning, btc-rpc-proxy takes 18443, the port dependents resolve, and
    # bitcoind steps aside to a loopback-only port behind it. The proxy answers
    # for blocks this node has dropped by fetching them from peers, so a
    # dependent sees a node that behaves as though it were archival. Unpruned,
    # there is nothing to fetch and bitcoind holds 18443 itself.
    echo "rpcbind=${RPC_BIND:-0.0.0.0}"
    echo "rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}"
    # The internal ports stay the same on every chain, rather than following
    # each chain's default. They are this package's contract with dependents,
    # and StartOS gives every package its own bridge address, so there is
    # nothing to collide with. A dependent should not have to re-read a port
    # because the operator switched chains.
    echo "rpcport=${RPC_PORT:-18443}"
    # Two p2p listeners. `bind` is the ordinary one, shared with anonymous
    # inbound peers. `whitebind` grants noban + download to whatever arrives on
    # it, and StartOS keeps that binding off the LAN, so it is reachable only by
    # other services on the bridge. A dependent pulling historical blocks needs
    # the second: on the first it is subject to inbound eviction, and on a pruned
    # node to NODE_NETWORK_LIMITED, which disconnects it for asking about a block
    # more than 288 deep.
    #
    # Both are explicit because naming either one disables bitcoind's default
    # listener, so omitting `bind` here would leave the node with no ordinary
    # p2p port at all.
    echo "bind=0.0.0.0:18444"
    echo "whitebind=0.0.0.0:18445"
    for node in $ADDNODES; do
        echo "addnode=${node}"
    done
    [ -n "${BLOCKNOTIFY_URL:-}" ] && echo "blocknotify=wget -q -T 2 -O /dev/null ${BLOCKNOTIFY_URL}"
} > "$CONF"

echo "knots-blake2b: pinned commit $(cat /etc/knots-pinned-commit)"
echo "knots-blake2b: chain=mainnet prune=${PRUNE} activation=961640 (compiled in)"
echo "knots-blake2b: addnodes=${ADDNODES:-none}"

# Not `exec`. A process running as PID 1 does not get the default action for a
# signal it has no handler for, so the kernel discards it. bitcoind installs a
# SIGTERM handler and would have been fine, but keeping the shell as PID 1 makes
# the shutdown path here identical to the gateway package's, where the service
# does not, and where getting this wrong cost a truncated shutdown.
bitcoind -datadir="$DATADIR" "$@" &
APP_PID=$!

# Forward what `docker stop` and StartOS send, so staying PID 1 does not turn a
# normal shutdown into a ten-second wait and a kill.
trap 'kill -TERM "$APP_PID" 2>/dev/null || true' TERM INT

# There is no settings watcher any more. It existed so that a page served by the
# gateway app could write a shared `settings.json` holding the chain and the
# prune target, which both containers watched and restarted on. The chain is not
# a setting any more, and on the two platforms this image runs on the prune
# target has a real settings form: a StartOS action, or the node app's own
# Advanced Settings on Umbrel. Both restart the service themselves.
#
# Exits when the service does, whether that is a crash or a stop. Either way the
# restart policy decides what happens next.
#
# The loop is the point, and one `wait` is not enough. A trapped signal makes
# `wait` return immediately with a status above 128, *without* reaping the child:
# the trap above has only asked the service to stop, and it is still running. If
# the script ended there, PID 1 would exit while the service was still shutting
# down, and the container would take it with it. For bitcoind that means the
# chainstate is never flushed, so a stop during a long sync throws the sync away
# and it starts over from the last flush, which during an initial sync is
# nothing. Measured: stopping at height 84900 mid-IBD came back at height 327.
#
# So wait again until the child is genuinely gone, and exit with its status
# rather than the signal's.
# `|| rc=$?` rather than a bare `wait`, and that is the whole fix. `set -e` is on
# (line 6), and an interrupted `wait` returns 128+signum, so a bare `wait` ends
# the script the instant the signal arrives, before anything can read its status.
# That is what used to happen: the trap asked the service to stop, `set -e` then
# killed PID 1 five milliseconds later, and the container took the service down
# mid-shutdown. A command on the left of `||` is exempt from `set -e`.
rc=0
wait "$APP_PID" || rc=$?
while [ "$rc" -gt 128 ] && kill -0 "$APP_PID" 2>/dev/null; do
    rc=0
    wait "$APP_PID" || rc=$?
done
exit "$rc"

