export const DEFAULT_LANG = 'en_US'

const dict = {
  'Get Payout Address': 0,
  'Create an address in this node’s wallet, to paste into the gateway as its payout address.': 1,
  'A block mined to this address pays its whole subsidy to a key held by this node’s wallet, and nowhere else. Back the wallet up before you rely on it.': 2,
  Wallet: 3,
  'Payout Address': 4,
  'Copy this into the gateway’s Set Payout Address action. Blocks mined will pay here.': 5,
  Address: 6,
  Storage: 7,
  'Whether to keep the whole chain on disk, or keep only recent blocks and discard the rest.': 8,
  'The node restarts to apply this. Going from keeping everything to keeping recent blocks deletes the older ones, and getting them back means downloading the chain again. Going the other way also means downloading the chain again, because the blocks that were discarded are gone.': 9,
  'Keep recent blocks only (pruned)': 10,
  'Blocks to keep': 11,
  'How much disk to allow for blocks, in MiB. Older blocks are discarded automatically once this is exceeded. This does not cover the rest of the node’s data, which grows on its own.': 12,
  'Keep the whole chain (archival)': 13,
  'Select Storage': 14,
  'Choose whether this node keeps the whole chain or only recent blocks.': 15,
  Configuration: 16,
  Peers: 17,
  'One address per line, as host:port. These are dialled in addition to the peers built into this service.': 18,
  'Set Peers': 19,
  'Add nodes to connect to, on top of the ones this service already knows. Only needed if the built-in peers stop working.': 20,
  'The node restarts to apply the change. A peer that is not on the BLAKE2b chain will not break anything, it simply cannot serve blocks after the activation height.': 21,
  'Show Wallet Balance': 22,
  'See what this node has mined.': 23,
  'Wallet Balance': 24,
  'This wallet is on the BLAKE2b chain. Its coins are spendable to anyone following that chain, and they are only as safe as your backup of this node’s wallet.': 25,
  'Mined so far': 26,
  'Spendable now': 27,
  'Not spendable yet': 28,
  'Freshly mined coins need 100 more blocks before they can be spent. This is normal, and it is where a new miner’s rewards sit.': 29,
  'Block height': 30,
  'How far this node has synced. BLAKE2b activated at block 961640.': 31,
  RPC: 32,
  'Bitcoin JSON-RPC. Used by the BLAKE2b gateway.': 33,
  Peer: 34,
  'P2P for connecting to other BLAKE2b nodes.': 35,
  'Starting Bitcoin Knots (BLAKE2b) Companion': 36,
  'The node is accepting RPC': 37,
  'The node is not accepting RPC yet': 38,
  Chain: 39,
  'Waiting for the node to answer RPC': 40,
  'This node reports no BLAKE2b activation. It is not running the fork.': 41,
  'This build activates BLAKE2b at a different height than expected on mainnet': 42,
  'Following the BLAKE2b chain': 43,
  Syncing: 44,
  'Stalled just below the BLAKE2b activation height, which means this node has no peers on the fork. It normally finds them through the DNS seeds. Add one directly with the Set Peers action if your network blocks DNS.': 45,
  'Before the BLAKE2b activation': 46,
  'RPC Proxy': 47,
  'Serving RPC, and fetching pruned blocks': 48,
  'The RPC proxy is not ready': 49,
}

/**
 * Plumbing. DO NOT EDIT.
 *
 * Generated by startos/gen-i18n-dict.py from the i18n() calls in this
 * package. Add a string by using it, then re-run that script.
 */
export type I18nKey = keyof typeof dict
export type LangDict = Record<(typeof dict)[I18nKey], string>
export default dict
