#!/usr/bin/env python3
"""Regenerate a package's i18n default dictionary from the strings actually used.

The dictionary is a map from every literal passed to `i18n(...)` to a stable
index. It is type-checked: a string used in the source but missing from the
dictionary is a compile error, and a string in the dictionary that nothing uses
is dead weight that survives every later edit. Keeping it by hand across a
change this size is how stale entries accumulate, so it is derived instead.

Usage: gen-i18n-dict.py <package-dir>

Only `en_US` is authored in these packages, and `translations.ts` is
deliberately empty (see its comment), so re-indexing cannot mistranslate
anything. If a package ever gains real translations, this script must not be
run without remapping them: the indices are the join key.
"""

import re
import sys
from pathlib import Path

CALL = re.compile(r"(?<![A-Za-z0-9_$])i18n\s*\(\s*(['\"])((?:\\.|(?!\1).)*)\1", re.S)


def unescape(raw: str, quote: str) -> str:
    """Turn a TS string literal body into the value it denotes."""
    out = []
    i = 0
    while i < len(raw):
        c = raw[i]
        if c == "\\" and i + 1 < len(raw):
            nxt = raw[i + 1]
            out.append({"n": "\n", "t": "\t", "r": "\r"}.get(nxt, nxt))
            i += 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def literal(value: str) -> str:
    """Render a dictionary key, quoting only when it has to be quoted."""
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value):
        return value
    body = value.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n")
    return f"'{body}'"


def main() -> int:
    pkg = Path(sys.argv[1]).resolve()
    src = pkg / "startos"
    if not src.is_dir():
        print(f"no startos/ under {pkg}", file=sys.stderr)
        return 1

    dict_path = src / "i18n" / "dictionaries" / "default.ts"

    seen: list[str] = []
    index: dict[str, int] = {}
    # Sorted for determinism: the same tree must produce the same file.
    for path in sorted(src.rglob("*.ts")):
        if path == dict_path:
            continue
        text = path.read_text(encoding="utf-8")
        for m in CALL.finditer(text):
            value = unescape(m.group(2), m.group(1))
            if value not in index:
                index[value] = len(seen)
                seen.append(value)

    lines = ["export const DEFAULT_LANG = 'en_US'", "", "const dict = {"]
    for i, value in enumerate(seen):
        lines.append(f"  {literal(value)}: {i},")
    # No `as const`. The scaffold's LangDict is `Record<(typeof dict)[I18nKey],
    # string>`, which widens to Record<number, string> without it and to a
    # union of literal indices with it. Narrowing that here would make every
    # locale owe an entry for every string.
    lines += [
        "}",
        "",
        "/**",
        " * Plumbing. DO NOT EDIT.",
        " *",
        " * Generated by startos/gen-i18n-dict.py from the i18n() calls in this",
        " * package. Add a string by using it, then re-run that script.",
        " */",
        "export type I18nKey = keyof typeof dict",
        "export type LangDict = Record<(typeof dict)[I18nKey], string>",
        "export default dict",
        "",
    ]
    dict_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"{dict_path.relative_to(pkg)}: {len(seen)} strings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
